language-map
Claudiohbsantos/github-material-icons-extension pull request #10
Opened 2021-06-25 01:34 UTC by 4086606

The [icon pack](https://github.com/PKief/vscode-material-icon-theme) doesn't include extensions that can instead be associated with a reconfigurable language ID.

Let's pull in mutually exclusive language configuration data from Microsoft repos so that this data can be used to compute and apply icons accurately.

2021-06-25 05:51 UTC, shivapoudel commented
@4086606 Just like we copied the `material-icons.json` into `iconMap.json` is there any repo we can look for to generate that language-related JSON it is because we don't wanna store those files here manually!

2021-06-25 10:34 UTC, 4086606 commented
👀 Don't hardcode those please!

It's compiled from every contributes.languages in the Microsoft organisation:

* Search for "contributes languages filename:package.json org:microsoft"
* Download the files to one place
* Scan for /([ \t]+)"languages": \[\n(.*\n)+?\1\]/
* Delete any folders with "sample" in the name
* Convert into lang-config map
* Move any file extensions not prefixed with . into file names *
* Remove anything that's mapped in material-icons.json *
* Do some remapping *
** properties extensions ^git -> git
** properties extensions ==editorconfig -> editorconfig
** properties extensions ^npm -> npm
** properties extensions -> settings
** properties names -> git
** vb -> visualstudio
** tablegen -> fsharp (custom)
** python -> python-misc (custom)
** shellscript -> console
** juliamarkdown -> julia (custom)
** git-commit -> git
** git-rebase -> git
** ignore -> vscode (custom)
* Do some merging:
** perl6 -> perl
** jsonc -> json
* Do some deletions: *
** Delete hlsl
** Delete log extensions
** Delete ignore extensions
* Remove definitions present in material-icons.json *

(Anything with a * after needs empty arrays removed as a post-completion step.)

2021-06-25 10:57 UTC, 4086606 commented
@Claudiohbsantos ideally this PR would precede the work in #7 and get merged first

2021-06-28 17:14 UTC, 4086606 commented
@shivapoudel I made the package able to generate the new config file automatically in 4da4285

2021-06-28 17:16 UTC, 4086606 commented
I also switched away from the camelcase naming convention because this repo ships with JSON files

2021-07-01 22:44 UTC, Claudiohbsantos commented
Thanks for the work on this. I'm travelling for a quick break until mid next week. I'll make sure to review this asap when I'm back

2021-07-09 03:48 UTC, Claudiohbsantos requested changes
This looks great, thanks! I ran it locally and tested on chrome without a problem! 

There is just a small issue on a missing return that is preventing `build` from running but once that's included I can approve :)

A small non-critical request: do you have the link to a repository in which the languages added can be seen as an example when compared to the current `master` version? If you don't have one handy you were using for testing don't worry about it

2021-07-09 03:48 UTC, Claudiohbsantos commented on scripts/extract-svg-html.js
> +        svgEntries.map((entry) => [
We're missing a return here, without which the `build-src` npm script fails

```suggestion
        return svgEntries.map((entry) => [
```

2021-07-09 08:07 UTC, 4086606 commented
I would be ideal to run the build scripts and publish all that to a `dev` branch. I'll have that done in an hour.

2021-07-09 08:36 UTC, 4086606 commented
@Claudiohbsantos done, see https://github.com/4086606/github-material-icons-extension/tree/dev

2021-07-09 23:22 UTC, Claudiohbsantos approved these changes

2021-07-09 23:23 UTC, Claudiohbsantos commented
Thanks for the changes. I'll merge this and then jump onto the other PR asap.

I'm not sure I understand the advantage of checking in generated files into git. Could you elaborate on how that would be better than having devs run the build scripts locally?

2021-07-09 23:24 UTC, merged

2021-07-10 03:23 UTC, 4086606 commented
That's a good idea. Could automate it all as a self updating repo via cron job

2021-07-10 09:29 UTC, 4086606 commented
That's what Phillip does over at the main repo. It's honestly super useful if you can't run the build scripts or download Chromium.

2021-07-14 01:54 UTC, Claudiohbsantos commented
@4086606 That makes sense. With the latest PR just merged downloading Chromium shouldn't be necessary anymore, which I believe will alleviate most of this issue. For now I'll hold off on checking in the generated files, just because I generally find more issues than benefits to having to wrangle them while navigating branches and their potentially different versions, and because I don't believe this project will have/need as much contribution as the VSCode extension, so I think keeping the repo simpler makes things easier for now. I appreciate the suggestion though, and will keep it in mind for the future 👍