Refactor code base for better enhancement and approach
Claudiohbsantos/github-material-icons-extension pull request #7
Opened 2021-06-21 14:57 UTC by shivapoudel

Yesterday night I tried to study for the browser extension work and studied this extension as I was interested in the MS Edge. My full efforts for making the codebase clean while understanding, I have also refactored many pieces of stuff to replace the packages we need, my friend :)

**_Please_** do a review and I am facing a problem with latest `svgo` config while building dependencies else other stuff are pretty good and impressive. Being in this branch will adapt latest version of `svgo` for optimizing SVG but with the latest version `2.3.0` . Previously master branch is at `1.3.2` so in the svgo 2.0.0 CLI --disable is deprecated and we are facing trouble with `npm run build-depedencies` and here goes the release note so that you can help on this https://github.com/svg/svgo/releases/tag/v2.0.0

2021-06-21 15:01 UTC, shivapoudel commented on scripts/build-dependencies.js
> +	.then(() => child_process.exec(`npx svgo --disable=removeViewBox .`, distIconsExecOptions))
@Claudiohbsantos I couldn't fix `$entry[1].firstChile.getAttribute('viewBox')` related error while running `npm run build-depedencies` because SVF files are not optimized in latest version of SVGO.

This command `--disable=removeViewBox` has been removed in SVGO 2.0.0 :)

2021-06-21 15:01 UTC, shivapoudel commented on scripts/build-dependencies.js
> +		git.clone(`https://github.com/PKief/vscode-material-icon-theme.git`, 'temp', ['--depth', '1'])
Let's clone the VSCode repo faster with `--depth` :)

2021-06-21 15:03 UTC, shivapoudel commented on scripts/build-extensionIcons.js
> +const sharp = require('sharp');
Instead of Inkspace let's use sharp as it is lightweight and can run only from node packages. Lets not aks user to install Inkspace as I am also not a too much greedy user for it, my friend :)

2021-06-21 15:17 UTC, shivapoudel commented on package.json
> +		"eslint": "7.29.0",
We can install **Renovatebot** on this repo and every update required is look by the bot so I am not insisting on `^~` symbol and `.npmrc` and `.nvmrc` file exists to be on the latest stable node and install the exact version of a package.

https://github.com/apps/renovate

2021-06-21 15:17 UTC, shivapoudel commented on .gitignore
> +# Directories/files that may be generated by this project
No need for global file ignorance. Let's ignore project required objectives only :)

2021-06-21 15:17 UTC, shivapoudel commented on LICENSE
> +Copyright (c) 2020 Claudio Santos, Shiva Poudel and Richard Lam
@Claudiohbsantos Lemme know if I am allowed :)

2021-06-21 15:17 UTC, shivapoudel commented on README.md
> -Rebuild extension logos from `src/logo.svg`. _This script needs [Inkscape](https://inkscape.org/) to be available on PATH_
Can get rid of this note :)

2021-06-21 15:17 UTC, shivapoudel commented on README.md
> +Zip `dist` folder for upload to Chrome Web Store and Firefox. _This script needs Zip to be available on PATH_
I am being greedy over here as I am a fan of `zip` command instead of 7z :)

2021-06-21 15:17 UTC, shivapoudel commented on package.json
> +	"description": "Browser Extension that enhances the GitHub file browser with material icons.",
It's not portrayed for all major browsers so why not?

2021-06-21 15:17 UTC, shivapoudel commented on package.json
> +	"author": "Claudio Santos",
Please accept this, I know how hard is to bring things into reality :)

2021-06-21 15:17 UTC, shivapoudel commented on package.json
> +	"name": "github-material-icons-extension",
Not only for chrome but for others thus renamed!

2021-06-21 15:39 UTC, Claudiohbsantos commented
@shivapoudel Thanks for opening this PR, I'll take a look as soon as I can (probably later this week). 

It seems you are using different indentation settings though, which makes the diff pretty large and makes it harder to review the PR since pretty much every line seems to be changed. Would you mind changing your editorconfig file to match the style of the existing codebase so the PR reflects only actual changes? That would make it much easier to jump into it when I have a chance :)

2021-06-21 22:42 UTC, shivapoudel commented on .npmrc
> +save-exact = true
Let's pass the control of package update to the renovate bot and just save the exact version of the package.

2021-06-21 22:42 UTC, shivapoudel commented on LICENSE
> +Copyright (c) 2021 Claudio Santos, Shiva Poudel and Richard Lam
@Claudiohbsantos Lemme know if I am allowed :)

2021-06-21 22:47 UTC, shivapoudel commented on package.json
> +  "name": "github-material-icons-extension",
Making this same as the repo name because I know this extension can be crafted for all browsers rather than only for chrome.

2021-06-21 22:48 UTC, shivapoudel commented on package.json
> +  "description": "Browser Extension that enhances the GitHub file browser with material icons.",
Description modified "Chrome Extension" -> "Browser Extension" :D

2021-06-21 22:49 UTC, shivapoudel commented on package.json
> +  "main": "src/main.js",
Our main source destination is `src/main.js` not the `index.js`.

2021-06-21 22:51 UTC, shivapoudel commented on package.json
> +  "author": "Claudio Santos",
Please accept this, I know how hard is to bring things into reality :)

2021-06-21 22:55 UTC, shivapoudel commented on renovate.json
> +}
We can install **Renovatebot** on this repo and every update required is look by the bot so I am not insisting on `^~` symbol and `.npmrc` and `.nvmrc` file exists to be on the latest stable node and install the exact version of a package.

https://github.com/apps/renovate

2021-06-21 22:56 UTC, shivapoudel commented on scripts/build-dependencies.js
> +    git.clone(`https://github.com/PKief/vscode-material-icon-theme.git`, 'temp', ['--depth', '1'])
@Claudiohbsantos I couldn't fix `$entry[1].firstChile.getAttribute('viewBox')` related error while running `npm run build-depedencies` because SVF files are not optimized in latest version of SVGO.

This command `--disable=removeViewBox` has been removed in SVGO 2.0.0 :)

2021-06-21 22:57 UTC, shivapoudel commented on scripts/build-dependencies.js
> +  .then(() => child_process.exec(`npx svgo --disable=removeViewBox .`, distIconsExecOptions))
@Claudiohbsantos I couldn't fix `$entry[1].firstChile.getAttribute('viewBox')` related error while running `npm run build-depedencies` because SVF files are not optimized in latest version of SVGO.

This command `--disable=removeViewBox` has been removed in SVGO 2.0.0 :)

2021-06-22 00:18 UTC, shivapoudel commented on scripts/build-dependencies.js
> +    git().clone(`https://github.com/PKief/vscode-material-icon-theme.git`, 'temp', ['--depth', '1'])
Let's clone the VSCode repo faster with `--depth` :)

2021-06-22 02:04 UTC, shivapoudel commented on scripts/build-dependencies.js
> +  .then(() => child_process.exec(`npx svgo --disable=removeViewBox .`, distIconsExecOptions))
Fixed with https://github.com/Claudiohbsantos/github-material-icons-extension/pull/7/commits/fb94c5ed63a6a0694b7b16a1bfe0d895af21041b

2021-06-22 03:27 UTC, shivapoudel commented on scripts/build-dependencies.js
> +  .then(() => child_process.execSync(`npm install --ignore-scripts`, vsExtExecOptions))
We don't overall need the testing environment of the VSCode extension so skipping script installation to skip chromium download for a puppeteer in VSCode ext repo.

2021-06-22 03:33 UTC, shivapoudel commented
@Claudiohbsantos Now you can proceed with the review. I have managed to fix the coding rulesets you have mentioned earlier including `svgo` error in its latest version which doesn't support `--disable` in CLI. Additionally, I have chosen a shallow clone of VSCode extension repo and npm installation without scripts for it to faster the build process of icons for us!

If there is anything missing, please suggest me and I will have a look!!

2021-06-23 00:03 UTC, Claudiohbsantos requested changes
This is a really good PR, thanks a lot. In particular I appreciate the optimizations to the building scripts and the organization improvements.

I made a few comments with changes that I'd love to see before we merge. I also haven't had a chance to pull this PR and run all the scripts in my machine (Windows) to make sure there are no regressions, I'll try to do that before the end of the week.

Feel free to respond to comments in their threads, that might be the easiest way to keep track of them.

Don't hurry to make these changes, I don't think I'll be able to look at them for a couple of days.

Thanks!

2021-06-23 05:26 UTC, shivapoudel commented on LICENSE
> +Copyright (c) 2021 Claudio Santos, Shiva Poudel and Richard Lam
Okay :)

2021-06-23 07:22 UTC, shivapoudel commented on renovate.json
> +}
Fixed https://github.com/Claudiohbsantos/github-material-icons-extension/pull/7/commits/a0bf1ece6c32283801fe7e756546dfbf0d874971

2021-06-23 07:29 UTC, shivapoudel commented on scripts/build-dependencies.js
> +const git = require('simple-git');
Ref https://github.com/Claudiohbsantos/github-material-icons-extension/pull/7/commits/1f1f8a002df28b01a25f7a1b27819f6bb05be90f

2021-06-23 07:31 UTC, shivapoudel commented on src/main.js
> + * @returns Replace icon with material icon.
Fixed https://github.com/Claudiohbsantos/github-material-icons-extension/pull/7/commits/74cbf5b88b705290c17040b15febf29786a2b3c9

2021-06-23 07:40 UTC, shivapoudel commented on src/main.js
> + * @param {*} fileRow File Row.
Fixed: https://github.com/Claudiohbsantos/github-material-icons-extension/pull/7/commits/8ab58dda1e67e1f946b21171c5f38749e2812b40

2021-06-24 19:37 UTC, shivapoudel commented on src/main.js
> +    activeIconPack: 'react_redux',
@Claudiohbsantos This is my personal favorite, haha but we need to make this either choosable or fetch from the config like I have stated previously in this thread https://github.com/Claudiohbsantos/github-material-icons-extension/issues/4#issuecomment-867153587

2021-06-25 01:27 UTC, Claudiohbsantos commented on src/main.js
> +    activeIconPack: 'react_redux',
that's nice! I actually never used any of the icon packs in vscode, probably why I didn't realize this was a possiblity.

I'll answer more in depth in the issue to keep this PR cleaner, I agree :)

2021-06-25 01:29 UTC, Claudiohbsantos commented
Thanks for all of these changes, this is looking great. Whenever you feel like it's ready for a full review again just re-request review and I'll jump in whenever I can.

2021-06-25 06:08 UTC, shivapoudel commented
@Claudiohbsantos I am ready with this PR so please give a full review from your side. Additionally, after merging the PR, help with some logic to implement a simple config file for `activeIconPack` as I will not be looking on that currently with this PR.

2021-06-30 04:36 UTC, shivapoudel commented
@Claudiohbsantos any updates when you can full review this PR, my friend :)

2021-07-01 22:45 UTC, Claudiohbsantos commented
Hey @shivapoudel . Thanks for the work on this. I'm travelling for a quick break until mid next week. I'll make sure to review this asap when I'm back. Sorry for the delay

2021-07-02 23:45 UTC, 4086606 commented
In the new build scripts, could you add console log comments that give the user an idea of what the scripts currently doing?

I do the same in #10 and it helped me greatly when I was debugging the build scripts 😄

2021-07-02 23:56 UTC, shivapoudel commented
@4086606 I wish I could but unfortunately, I have some other prior tasks which I have to wrap up till the next week. However, that can be done after the merge also so will give a look at that on some other days, my friend :)

2021-07-09 23:26 UTC, Claudiohbsantos commented
@shivapoudel sorry about the delay. I just merged the other PR that preceded this one and will jump on this next. If I can't finish reviewing today I'll do it Monday the latest. Thank you for your patience

2021-07-13 01:56 UTC, Claudiohbsantos approved these changes
Looks great, thanks!

2021-07-13 03:26 UTC, Claudiohbsantos commented
If you'd like, I created a PR in your fork with the solution to the merge conflicts flagged here: https://github.com/shivapoudel/github-material-icons-extension/pull/2 . I thought that was easier for you than having to review the PR once again :) , and nicer than pushing the changes directly into this PR. Let me know if anything seems wrong to you.

I'm also happy to merge those changes directly into the PR if that's easier, I already tested the changes and they work as expected

2021-07-13 03:49 UTC, shivapoudel commented
@Claudiohbsantos I have tested the PR raised in the fork and seems nicer. Please proceed :)

2021-07-13 04:03 UTC, shivapoudel commented
@Claudiohbsantos Is download Chromium still necessary?
![image](https://user-images.githubusercontent.com/3774827/125388573-73715d00-e3bf-11eb-8287-584cfeab0576.png)

2021-07-13 04:15 UTC, Claudiohbsantos commented
Oh, i don't think so, thanks for catching that. Looks like I accidentally removed the --ignore-scripts option you added during the merge. I can re-add that after merging

2021-07-13 04:21 UTC, shivapoudel commented
@Claudiohbsantos While running `npm run build` I am facing this issue with module `make-dir` we already have `mkdirp` so can this be the one package that does both works?
![image](https://user-images.githubusercontent.com/3774827/125390074-f3002b80-e3c1-11eb-828d-d756c697d353.png)

2021-07-13 05:36 UTC, 4086606 commented
`make-dir` > `mkdirp`:
* https://github.com/substack/node-mkdirp/issues/66
* https://github.com/substack/node-mkdirp/issues/70
* https://github.com/substack/node-mkdirp/pull/96

2021-07-13 05:48 UTC, shivapoudel commented
@4086606 Is this okay for you https://github.com/Claudiohbsantos/github-material-icons-extension/pull/7/commits/ebef814f1bad8fcf4d688eaa385dd582c3dc55e9 as for me on Windows now it is working great!!

2021-07-13 05:49 UTC, shivapoudel commented
@Claudiohbsantos Merge conflicts and other issues have been patched. Please have a review and merge the PR :)

2021-07-13 06:55 UTC, 4086606 commented
Some small issues in Ubuntu (WSL), will open a pull to fix those

2021-07-14 01:48 UTC, Claudiohbsantos commented
This looks awesome, thanks for all the work on it and the many revisions

2021-07-14 01:48 UTC, merged